INSERT INTO CommunityCenters (Id, Name, Address, Settlement, Description, CreatedAt)
VALUES (NEWID(), 'Dom kulture Bjelovar', 'Trg Hrvatskih Branitelja 12', 'Bjelovar', 'Veliki dom za kulturna okupljanja u Bjelovaru', GETDATE()),
       (NEWID(), 'Gradska kuća Bjelovar', 'Ul. Ivana Gundulića 23', 'Bjelovar', 'Glavna gradska kuća za svečane događaje', GETDATE()),
       (NEWID(), 'Kulturni centar Stari Grad', 'Kralja Tomislava 5', 'Bjelovar', 'Centar za kulturne i umjetničke događaje u Starom Gradu', GETDATE()),
       (NEWID(), 'Društveni dom Borik', 'Borik 21', 'Bjelovar', 'Društveni dom u naselju Borik za sportske i kulturne aktivnosti', GETDATE()),
       (NEWID(), 'Kulturni dom Bilogora', 'Bilogorska ulica 9', 'Bjelovar', 'Dom na Bilogori za okupljanje lokalnih zajednica', GETDATE()),
       (NEWID(), 'Gradski centar Nova Rača', 'Nova Rača 14', 'Bjelovar', 'Gradski centar za događanja i manifestacije u Novoj Rači', GETDATE()),
       (NEWID(), 'Centar za mlade Bjelovar', 'Ul. Matice Hrvatske 17', 'Bjelovar', 'Moderno opremljeni centar za mlade', GETDATE()),
       (NEWID(), 'Dom sportova Bjelovar', 'Sportska 3', 'Bjelovar', 'Sportski centar s prostorima za kulturna događanja', GETDATE()),
       (NEWID(), 'Društveni centar Ždralovi', 'Ulica Ždralovi 25', 'Bjelovar', 'Društveni centar u naselju Ždralovi', GETDATE()),
       (NEWID(), 'Kulturni dom Rovišće', 'Rovišće 2A', 'Bjelovar', 'Dom za kulturne manifestacije u naselju Rovišće', GETDATE()),
       (NEWID(), 'Dom mladih Bjelovar', 'Ul. Alojzija Stepinca 19', 'Bjelovar', 'Dom mladih s modernim sadržajima za radionice', GETDATE()),
       (NEWID(), 'Gradski paviljon Bjelovar', 'Paviljonska 4', 'Bjelovar', 'Središnji gradski paviljon za kulturna događanja', GETDATE()),
       (NEWID(), 'Kulturni centar Korenovo', 'Korenovo 7', 'Bjelovar', 'Kulturni centar u naselju Korenovo', GETDATE()),
       (NEWID(), 'Društveni centar Gornje Plavnice', 'Plavnice 11', 'Bjelovar', 'Centar za društvene i kulturne aktivnosti', GETDATE()),
       (NEWID(), 'Gradski centar Veliko Trojstvo', 'Veliko Trojstvo 8', 'Bjelovar', 'Gradski centar u naselju Veliko Trojstvo', GETDATE()),
       (NEWID(), 'Dom kulture Centar', 'Ul. Petra Preradovića 10', 'Bjelovar', 'Glavni dom kulture u centru Bjelovara', GETDATE()),
       (NEWID(), 'Društveni centar Severin', 'Severin 15', 'Bjelovar', 'Društveni centar za lokalna okupljanja', GETDATE()),
       (NEWID(), 'Kulturni dom Sjever', 'Sjeverna ulica 4', 'Bjelovar', 'Kulturni dom u sjevernom dijelu grada', GETDATE()),
       (NEWID(), 'Dom zajednice Bjelovar', 'Zajednička ulica 6', 'Bjelovar', 'Dom za okupljanje lokalne zajednice', GETDATE()),
       (NEWID(), 'Kulturni centar Prgomelje', 'Prgomelje 12', 'Bjelovar', 'Centar za kulturne manifestacije u naselju Prgomelje', GETDATE()),
       (NEWID(), 'Društveni dom Tomaš', 'Tomaš 5', 'Bjelovar', 'Društveni dom u naselju Tomaš', GETDATE()),
       (NEWID(), 'Gradska kuća Gudovac', 'Gudovac 10', 'Bjelovar', 'Kuća za društvena i kulturna okupljanja', GETDATE()),
       (NEWID(), 'Kulturni centar Brezovac', 'Brezovačka 18', 'Bjelovar', 'Kulturni centar u naselju Brezovac', GETDATE()),
       (NEWID(), 'Dom kulture Bedenik', 'Bedenik 9', 'Bjelovar', 'Dom kulture u naselju Bedenik', GETDATE()),
       (NEWID(), 'Kulturni dom Kapela', 'Kapela 3', 'Bjelovar', 'Dom za kulturne aktivnosti u naselju Kapela', GETDATE()),
       (NEWID(), 'Centar za umjetnost Bjelovar', 'Ulica Vladimira Nazora 16', 'Bjelovar', 'Centar za suvremenu umjetnost u Bjelovaru', GETDATE()),
       (NEWID(), 'Dom kulture Staro Pračno', 'Staro Pračno 22', 'Bjelovar', 'Dom kulture u naselju Staro Pračno', GETDATE()),
       (NEWID(), 'Društveni centar Veliki Grđevac', 'Veliki Grđevac 13', 'Bjelovar', 'Društveni centar za lokalna događanja', GETDATE()),
       (NEWID(), 'Gradska dvorana Ivanska', 'Ivanska 6', 'Bjelovar', 'Gradska dvorana za sportske i kulturne aktivnosti', GETDATE()),
       (NEWID(), 'Kulturni centar Daruvar', 'Daruvarska 11', 'Bjelovar', 'Centar za kulturne događaje u Daruvaru', GETDATE()),
       (NEWID(), 'Društveni dom Malo Trojstvo', 'Malo Trojstvo 14', 'Bjelovar', 'Društveni dom u naselju Malo Trojstvo', GETDATE()),
       (NEWID(), 'Kulturni centar Brzičevo', 'Brzičevo 8', 'Bjelovar', 'Kulturni centar u naselju Brzičevo', GETDATE()),
       (NEWID(), 'Društveni centar Sirač', 'Sirač 17', 'Bjelovar', 'Centar za društvena okupljanja u naselju Sirač', GETDATE()),
       (NEWID(), 'Dom zajednice Predavac', 'Predavac 7', 'Bjelovar', 'Zajednički dom za lokalna okupljanja', GETDATE()),
       (NEWID(), 'Kulturni dom Malo Korenovo', 'Malo Korenovo 18', 'Bjelovar', 'Dom kulture u naselju Malo Korenovo', GETDATE()),
       (NEWID(), 'Gradski centar Veliko Korenovo', 'Veliko Korenovo 19', 'Bjelovar', 'Gradski centar u naselju Veliko Korenovo', GETDATE()),
       (NEWID(), 'Kulturni centar Žabjak', 'Žabjak 12', 'Bjelovar', 'Kulturni centar za lokalna događanja', GETDATE()),
       (NEWID(), 'Društveni dom Kokinac', 'Kokinac 23', 'Bjelovar', 'Društveni dom u naselju Kokinac', GETDATE()),
       (NEWID(), 'Kulturni centar Lipovljani', 'Lipovljani 14', 'Bjelovar', 'Dom za kulturne manifestacije u Lipovljanima', GETDATE()),
       (NEWID(), 'Društveni dom Breštanovci', 'Breštanovci 9', 'Bjelovar', 'Društveni dom u naselju Breštanovci', GETDATE()),
       (NEWID(), 'Gradski paviljon Vrbica', 'Vrbica 11', 'Bjelovar', 'Paviljon za gradska događanja u naselju Vrbica', GETDATE()),
       (NEWID(), 'Kulturni dom Babinac', 'Babinac 13', 'Bjelovar', 'Kulturni dom za lokalne manifestacije', GETDATE()),
       (NEWID(), 'Društveni centar Paljevine', 'Paljevine 16', 'Bjelovar', 'Društveni centar za male zajednice', GETDATE()),
       (NEWID(), 'Dom zajednice Hercegovac', 'Hercegovac 12', 'Bjelovar', 'Zajednički dom za kulturna i društvena okupljanja', GETDATE()),
       (NEWID(), 'Kulturni dom Međurača', 'Međurača 6', 'Bjelovar', 'Kulturni centar u naselju Međurača', GETDATE()),
       (NEWID(), 'Gradska kuća Obrovac', 'Obrovac 7', 'Bjelovar', 'Gradska kuća za lokalne manifestacije', GETDATE()),
       (NEWID(), 'Društveni centar Kupinovac', 'Kupinovac 4', 'Bjelovar', 'Društveni centar za kulturna događanja', GETDATE());

DECLARE
@userId UNIQUEIDENTIFIER;
SET
@userId = 'EDB088B9-65F3-4E74-8C75-3563D2AF6644';

INSERT INTO Reservations (Id, UserId, CommunityCenterId, ReservationFrom, ReservationTo, ExpectedNumberOfPeople, AdditionalNotes, CreatedAt)
SELECT NEWID(),
       @userId,
       c.Id,
       DATEADD(DAY, FLOOR(RAND(CHECKSUM(NEWID())) * 30) - 15, GETDATE()),
       DATEADD(DAY, FLOOR(RAND(CHECKSUM(NEWID())) * 5) + 1, DATEADD(DAY, FLOOR(RAND(CHECKSUM(NEWID())) * 30) - 15, GETDATE())),
       FLOOR(RAND(CHECKSUM(NEWID())) * 100) + 10,
       'Rezervacija za lokalni događaj',
       GETDATE()
FROM (SELECT TOP 25 Id FROM CommunityCenters ORDER BY NEWID()) c;